server:
  port: 8888

mouse:
  rocketmq:
    producer:
      isOnOff: no
      groupName: pay_producer_group #发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
      namesrvAddr: localhost:9876 #mq的nameserver地址
      maxMessageSize: 4096 #消息最大长度 默认1024*4(4M)
      sendMsgTimeout: 3000 #发送消息超时时间,默认3000
      retryTimesWhenSendFailed: 2 #发送消息失败重试次数，默认2
    consumer:
      isOnOff: no